# Generated by Django 5.0 on 2023-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='eshop_project/products/%Y-%m-%d', verbose_name='تصویر محصول'),
        ),
    ]
